catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
overrides:
  vite: 'catalog:'
shamefullyHoist: true
allowBuilds:
  esbuild: true
  simple-git-hooks: true
minimumReleaseAgeExclude:
