catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.6
  vite-plus: 0.2.6
overrides:
  vite: 'catalog:'
shamefullyHoist: true
allowBuilds:
  esbuild: true
  simple-git-hooks: true
minimumReleaseAgeExclude:
  - '@soybeanjs/changelog@0.5.2'
